# permissions for end users to view serviceproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceproxy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frp-operator
    app.kubernetes.io/part-of: frp-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceproxy-viewer-role
rules:
- apiGroups:
  - core.faione.frp
  resources:
  - serviceproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.faione.frp
  resources:
  - serviceproxies/status
  verbs:
  - get
