apiVersion: core.faione.frp/v1
kind: ServiceProxy
metadata:
  labels:
    app.kubernetes.io/name: serviceproxy
    app.kubernetes.io/instance: serviceproxy-sample
    app.kubernetes.io/part-of: frp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: frp-operator
  name: serviceproxy-sample
spec:
  frps:
    name: frpservice-sample
    namespace: default
  proxies:
    - name: "example_server"
      localIp: echoserver-service
      localPort: "8080"
      remotePort: "8888"
